global:
  checkNewVersion: false
  sendAnonymousUsage: true

api:
  dashboard: false
  insecure: false

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        &trustedIps # Start of Clouflare public IP list for HTTP requests, remove this if you don't use it
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 108.162.192.0/18
        - 131.0.72.0/22
        - 141.101.64.0/18
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 173.245.48.0/20
        - 188.114.96.0/20
        - 190.93.240.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # End of Cloudlare public IP list
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    forwardedHeaders:
      # Reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: domain_name.com
            sans:
              - "*.domain_name.com"
      middlewares:
        - default

providers:
  providersThrottleDuration: 2s
  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    endpoint: "tcp://dockersocket:2375"
    exposedByDefault: false
    network: secure
    watch: true
  # File provider for connecting things that are outside of docker / defining middleware
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: your_email@domain.com
      storage: /etc/traefik/ssl/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# Log level INFO|DEBUG|ERROR
log:
  level: DEBUG
  filePath: "/var/log/traefik/traefik.log"
  format: common
  maxSize: 50
  maxBackups: 14
  maxAge: 1
  compress: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
  format: common
  filters:
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: "10ms"
  fields:
    names:
      StartUTC: drop
